/*
 * File: main.S
 * Created Date: 2023-10-09 03:34:09 pm
 * Author: Mathieu Escouteloup
 * -----
 * Last Modified: 2023-10-09 04:34:30 pm
 * Modified By: Mathieu Escouteloup
 * -----
 * License: See LICENSE.md
 * Copyright (c) 2023 HerdWare
 * -----
 * Description: 
 */

#include "cpu.h"
#include "main.h"

## ******************************
##             CODE
## ******************************
.globl main
main:
  ret

## ******************************
##             DATA
## ******************************
.section .data

.section .rodata